from db_credentials import database_credentials

table_name_auction = "table_auction_surplex"

auction_table_cols = [
    "auction_id", "name", "denomination", "article_number", "maker", "model", "production_year",
    "availability", "commission_percentage", "disassembly_loading_costs", "total_price",
    "transportation_expenses", "delivery_conditions", "payment_conditions", "dimensions",
    "weight_approx", "batch_name", "batch_link", "lot_no", "document_links", "inspection",
    "pickup", "category", "type", "start_date", "end_date", "followers", "total_bids",
    "current_bid", "bid_up", "bid_option_1", "bid_option_2", "bid_option_3", "sku", "city",
    "state", "country", "location", "description", "item_details", "technical_details",
    "expense_benefits", "auction_details", "image_links", "agent_name", "agent_role", "agent_phone",
    "agent_mobile", "agent_email", "updated_at", "url",
]

table_schemas = [
    f"""
    CREATE TABLE IF NOT EXISTS `{database_credentials["database"]}`.`{table_name_auction}` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `auction_id` VARCHAR(100) NULL,
    `name` TEXT NOT NULL,
    `denomination` TEXT NULL,
    `article_number` VARCHAR(100) NULL,
    `maker` VARCHAR(500) NULL,
    `model` VARCHAR(500) NULL,
    `production_year` VARCHAR(500) NULL,
    `availability` VARCHAR(500) NULL,
    `commission_percentage` VARCHAR(100) NULL,
    `disassembly_loading_costs` VARCHAR(500) NULL,
    `total_price` VARCHAR(500) NULL,
    `transportation_expenses` TEXT NULL,
    `delivery_conditions` TEXT NULL,
    `payment_conditions` TEXT NULL,
    `dimensions` VARCHAR(500) NULL,
    `weight_approx` VARCHAR(100) NULL,
    `batch_name` TEXT NULL,
    `batch_link` TEXT NULL,
    `lot_no` VARCHAR(100) NULL,
    `document_links` TEXT NULL,
    `inspection` TEXT NULL,
    `pickup` TEXT NULL,
    `category` VARCHAR(500) NULL,
    `type` VARCHAR(500) NULL,
    `start_date` VARCHAR(50) NULL,
    `end_date` VARCHAR(50) NULL,
    `followers` VARCHAR(50) NULL,
    `total_bids` VARCHAR(50) NULL,
    `current_bid` VARCHAR(50) NULL,
    `bid_up` VARCHAR(50) NULL,
    `bid_option_1` VARCHAR(50) NULL,
    `bid_option_2` VARCHAR(50) NULL,
    `bid_option_3` VARCHAR(50) NULL,
    `sku` VARCHAR(50) NULL,
    `city` VARCHAR(500) NULL,
    `state` VARCHAR(500) NULL,
    `country` VARCHAR(500) NULL,
    `location` TEXT NULL,
    `description` TEXT NULL,
    `item_details` TEXT NULL,
    `technical_details` TEXT NULL,
    `expense_benefits` TEXT NULL,
    `auction_details` TEXT NULL,
    `image_links` TEXT NULL,
    `agent_name` VARCHAR(500) NULL,
    `agent_role` VARCHAR(500) NULL,
    `agent_phone` VARCHAR(100) NULL,
    `agent_mobile` VARCHAR(100) NULL,
    `agent_email` VARCHAR(500) NULL,
    `url` VARCHAR(1000) NULL,
    `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
     PRIMARY KEY (`id`));
    """,
]
